### ISSUE TITLE
Списание на сумму большую чем заблокировано на счете (withdraw_id=146)

### ISSUE THREAD

**Issue by dapi** [bitzlato/peatio#151]
23-го сентября появилось списание, которое не прошло по причине отсутствия суммы на блокчейн-кошельке и ушло в статус `errored`.

Отмена этого списанная вручную (через `fail!` или через Tower) не удалась так как оказалось что залоченная в акаунте сумма была меньше чем сумма списания:

```
w= Withdraw.find(146)
w.amount.to_s
=> "0.294536"

w.account.locked
> "0.269236"
```

**Comment by dapi** [comment]
root@ex2:/home/ubuntu# grep -r 'Cannot unlock funds' /tmp/syslog.tmp 
Sep 23 06:19:43 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 06:19:43","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0029, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 06:19:44 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 06:19:44","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0032, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 06:19:45 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 06:19:45","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0024, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 06:52:12 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 06:52:12","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0162, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 06:52:17 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 06:52:17","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0024, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 06:52:17 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 06:52:17","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0032, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 06:52:18 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 06:52:18","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0029, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:23:26 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:23:26","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0029, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:32:12 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:12","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0048, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:32:21 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:21","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0024, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:32:22 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:22","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0032, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:32:23 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:23","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0029, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:32:26 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:26","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0029, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:32:34 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:34","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0048, balance: 0.2970366 locked: 0.0017).>"}
```

**Comment by dapi** [comment]
```
Sep 23 08:32:34 ex2 peatio-amqp_daemon-trade_executor[3922422]: {"level":"INFO","time":"2021-09-23 08:32:34","message":"Received: {\"action\":\"cancel\",\"order\":{\"id\":4235686,\"timestamp\":1631259176,\"type\":\"ask\",\"volume\":\"0.0048\",\"price\":\"5000.0\",\"market\":\"eth_usdcerc20\",\"ord_type\":\"limit\"}}"}
Sep 23 08:32:34 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"INFO","time":"2021-09-23 08:32:34","message":"Received: {\"action\":\"cancel\",\"order\":{\"id\":4235686,\"timestamp\":1631259176,\"type\":\"ask\",\"volume\":\"0.0048\",\"price\":\"5000.0\",\"market\":\"eth_usdcerc20\",\"ord_type\":\"limit\"}}"}
Sep 23 08:32:34 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:34","message":"#<Account::AccountError: Cannot unlock funds (member id: 20, currency id: eth, amount: 0.0048, balance: 0.2970366 locked: 0.0017).>"}
Sep 23 08:32:34 ex2 peatio-amqp_daemon-order_processor[3922421]: {"level":"ERROR","time":"2021-09-23 08:32:34","message":"/home/app/peatio/releases/20210922064409/app/models/account.rb:117:in `attributes_after_unlock_funds!'\n/home/app/peatio/releases/20210922064409/app/models/account.rb:108:in `unlock_funds!'\n/home/app/peatio/releases/20210922064409/app/models/order.rb:144:in `block in cancel'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'\n/home/app/peatio/releases/20210922064409/app/models/order.rb:143:in `cancel'\n/home/app/peatio/releases/20210922064409/app/workers/amqp/order_processor.rb:22:in `process'\n./lib/daemons/amqp_daemon.rb:70:in `block (2 levels) in <main>'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer.rb:56:in `call'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/channel.rb:1768:in `block in handle_frameset'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `loop'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `catch'\n/home/app/peatio/shared/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `run_loop'"}
```

**Comment by radanisk** [comment]
При корректировке https://github.com/bitzlato/peatio/wiki/Корректировка-депозита-%23557-(ошибочное-зачисление-газа-как-депозита) на аккаунте было разлочено 0.0278 эфира. При этом order'ы, вызвавшие блокировку этой суммы, тогда не отменились. Всё это вызвала вышеописанные ситуации, когда было недостаточно залоченного эфира на аккаунте для разблокировки или залоченная в акаунте сумма была меньше, чем сумма списания.
